apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tigera-operator

resources:
  - base-manifests/tigera-operator.yaml
#  - base-manifests/custom-resources.yaml
  - base-manifests/apiserver.yaml
# убираем deprecated ключ
patches:
  - path: calico-crs-patch.yaml
    target:
      kind: Installation
      name: default
