apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tigera-operator
configurations:
  - config/namespaced-only.yaml   # <-- новое
resources:
  - base-manifests/tigera-operator.yaml
  - base-manifests/custom-resources.yaml
  - base-manifests/apiserver.yaml
# убираем deprecated ключ
