apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tigera-operator

resources:
  - ../../base/tigera-operator.yaml
  - ../../base/custom-resources.yaml

patchesStrategicMerge:
  - calico-crs-patch.yaml
